#!/bin/sh

# colors
INFOC="\x1b[1;36m"
NC="\x1b[m"

# info function
info(){
    printf "${INFOC}${1}${NC}\n"
}

# zsh and plugins
info "Installing zsh and plugins..."
sudo pacman -S zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-theme-powerlevel10k

